### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by ruoniao** [iHealth-ecnu/iHealth_site#14]
我在使用Django+mongoDB时遇到一些问题，向你请教
比如你修改手机号，或者修改个人信息，一定要完成用户认证，认证这个用户修改自己的信息。
在前在mysql中的model中会有session验证机制，现在使用mongodb数据库怎样完成这样的用户认证呢?

**Comment by elliotxx** [comment]
目前的做法是在客户端和接口上做限制，客户端只有在用户登录过生成cookie才能修改信息，并且调用修改用户信息的API时需要传递用户名和密码，通过验证后才能修改。
如果你有更好的想法，欢迎讨论~

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
